services:
  database:
    container_name: "moneygoals-dev-db"
    image: postgres:18.1-alpine3.23
    env_file:
      - ../envs/.env.development
    ports:
      - 5432:5432
    volumes:
      - ../data/postgres:/var/lib/postgresql/data